### PR TITLE
- Re-introducing "CapabilitySlackChannelId" and constrain needed matc…

### PR DESCRIPTION
**Pull request by ZaradarDFDS**
- Added new column to CapabilityMember table to satisfy Capability PKey constraint.
- Re-introduced FK constraint on CapabilityMember table
- Re-introduced CapabilitySlackChannelId column in CapabilityMember.csv

### CODE REVIEW

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |3|
| **Quality Gates** |OK|
| **Description** |Low Risk: The change is low risk as it touches fewer modules and code than 24% of your change sets.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |4|
| **Quality Gates** |OK|
| **Description** |Low Risk: The change is low risk as it touches fewer modules and code than 16% of your change sets.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Comment by SEQUOIIA** [comment]
Upon further investigation, "member_joined_capability" not working makes a lot of sense upon looking at the event handler.
Screenshot 2020-05-26 at 10 32 13 PM

Line 57. Any database operation within the event handler is only occurring within that *if* scope. An *if* that will only run if SlackUserGroupId is null or empty, which for any ordinary case, it won't empty nor null.

**Comment by ZaradarDFDS** [comment]
First of all, epic work my young padiwan. You will make a great jedi ninja sooner, rather then later. Now for some feedback on your excellent input! The fact that our DBContext is now working means that the schema is back to a state that is compatible with the LINQ-2-Entities provider EF Core uses, which due to the nature of the PKey relationship in the Capability entity configuration forces navigation properties to have not 1, but 2 foreign keys, which is hard to know if your doing migrations manually. Buuuut I have been there already, said what I need to say and lets leave it at that for now. Bottom line is re-introducing the missing FKey values in CapabilityMember made the Capability configuration work again. So great! :)

Secondly this also means inclusion properties should be working. Since we are asking it to eager load the CapabilityMember, check the code in the CapabililtyEFRepo. 

With regards to the problem you experienced with the "member_left_capability" eventhandler this is most likely due to the fact that as such a local HaraldDb instance is only seeded with a single capability (id: 0d03e3ad-2118-46b7-970e-0ca87b59a202), which maps to a single member (toban@dfds.com). Thus its most likely doing as intended and returning null from the initial call to the repo because well there are no capabilities matching that id. :)

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |5|
| **Quality Gates** |OK|
| **Description** |Medium Risk (5 where 10 is the highest): The risk is lower since it is an experienced author responsible for 12% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul><br/>Absence of Expected Change Pattern<br/><ul><li>harald/src/Harald.WebApi/Application/EventHandlers/SlackMemberLeftCapabilityDomainEventHandler.cs</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |6|
| **Quality Gates** |OK|
| **Description** |Medium Risk (6 where 10 is the highest): The change involves more modules than 95% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 13% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul><br/>Absence of Expected Change Pattern<br/><ul><li>harald/src/Harald.WebApi/Application/EventHandlers/SlackMemberLeftCapabilityDomainEventHandler.cs</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |6|
| **Quality Gates** |OK|
| **Description** |Medium Risk (6 where 10 is the highest): The change involves more modules than 97% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 13% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul><br/>Absence of Expected Change Pattern<br/><ul><li>harald/src/Harald.WebApi/Application/EventHandlers/SlackMemberLeftCapabilityDomainEventHandler.cs</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |7|
| **Quality Gates** |OK|
| **Description** |Medium Risk (7 where 10 is the highest): The change involves more modules than 98% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 31% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |7|
| **Quality Gates** |OK|
| **Description** |Medium Risk (7 where 10 is the highest): The change involves more modules than 98% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 31% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |7|
| **Quality Gates** |OK|
| **Description** |Medium Risk (7 where 10 is the highest): The change involves more modules than 98% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 31% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |7|
| **Quality Gates** |OK|
| **Description** |Medium Risk (7 where 10 is the highest): The change involves more modules than 98% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 31% of all commits in this repo.|
| **Warnings** |Delta Analysis Info<br/><ul><li>2 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping quality gate checks for those files.</li></ul>|

**Pull request merged**
