### PR TITLE
Remove email addresses in various files

### PR DESCRIPTION
**Pull request by abstrask**

### CODE REVIEW

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |2|
| **Quality Gates** |OK|
| **Description** |Low Risk: No code is modified, only deleted (357) lines of code.|

**Comment by wcarlsen** [comment]
You would possible break local dev environment by removing seed data and initial database migration shooting the seed data into the Postgres db?

**Comment by abstrask** [comment]
What is the alternative, to keeping a list of real email addresses, in our public repo?

**Comment by SEQUOIIA** [comment]
I don't disagree with removing them at all, and even find it a bit weird that we've got actual data in our migration files.

If we are going to remove it though, we might as well go all the way instead of doing it by a commit. With the current solution doing a "*@dfds.com" search in this repo would still show the emails, just in a prior commit.

Do something like shown here - https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history

People with a local copy of the Harald repo already would have to do a force reset on their local copy in order to pull from the repo after doing that. Also a copy of it would still be stuck in the [Arctic Vault](https://archiveprogram.github.com/arctic-vault/) probably 😅 
image

**Review by wcarlsen — APPROVED** [review]

**Comment by wcarlsen** [comment]
Data should of course be mocked, but I was more thinking of the broader picture in terms of development.

**Comment by abstrask** [comment]
Good point, @wcarlsen. Should we replace valid mail addresses in the list with made-up, non-existent ones? @SEQUOIIA ?

**Comment by SEQUOIIA** [comment]
> 
> 
> Should we replace valid mail addresses in the list with made-up, non-existent ones? @SEQUOIIA ?

I'll have to do some testing, but I don't think *db/migrations/20200522133859_seed_members_data.sql* should be necessary at all. 

Removing *db/seed/CapabilityMember.csv* should also be fine. I don't see it having a place in our local development world at the current moment since we're using our own identity when running Blaster locally, and thus the only entry in that file would currently only work for @ZaradarDFDS

**Comment by abstrask** [comment]
@SEQUOIIA I'm aware this can still be found in the commit history. I think that as long as we strive to not do this in the future it's OK. Are you OK with me merging the PR?

**Comment by wcarlsen** [comment]
@abstrask and @SEQUOIIA should we either merge or close?

**Pull request merged**
