### PR TITLE
Changed deprecated endpoints

### PR DESCRIPTION
**Pull request by wcarlsen**
Can we test this out together @SEQUOIIA ? Fixes https://github.com/dfds/cloudplatform/issues/290

### CODE REVIEW

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |0|
| **Quality Gates** |OK|
| **Description** |Defaulting to Low Risk since this looks like a sweeping rename without logic changes|

**Comment by SEQUOIIA** [comment]
Daaamn you fast boi

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |0|
| **Quality Gates** |OK|
| **Description** |Defaulting to Low Risk since this looks like a sweeping rename without logic changes|

**Comment by wcarlsen** [comment]
This does not fix the missing consumer lag issue.

**Comment by SEQUOIIA** [comment]
👍 

Did you check if it accepts the same payloads or did you just change to the different endpoint specified in the changelog?

**Comment by wcarlsen** [comment]
The documentation doesn't specify any as far as I see.

**Comment by wcarlsen** [comment]
https://api.slack.com//changelog//2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by SEQUOIIA** [comment]
Only looked at conversations.create/channels.create

https://github.com/dfds/harald/blob/ea8e410f99734ae3ed27fc9af7c85e66f167b6f9/src/Harald.Infrastructure.Slack/Http/Request/Channel/CreateChannelRequest.cs#L11

Doesn't seem like 'validate' is a valid argument in conversations.create

**Comment by wcarlsen** [comment]
ARghhh yes I see. I overlooked validate. FUCK!

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |0|
| **Quality Gates** |OK|
| **Description** |Defaulting to Low Risk since this looks like a sweeping rename without logic changes|

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |High Risk (8 where 10 is the highest): The change involves more modules than 99% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 25% of all commits in this repo.|

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |High Risk (8 where 10 is the highest): The change involves more modules than 99% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 25% of all commits in this repo.|

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |High Risk (8 where 10 is the highest): The change involves more modules than 99% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 25% of all commits in this repo.|

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |8|
| **Quality Gates** |OK|
| **Description** |High Risk (8 where 10 is the highest): The change involves more modules than 99% of the historic high-risk change sets. The risk is lower since it is an experienced author responsible for 25% of all commits in this repo.|

**Review by ZaradarDFDS — APPROVED** [review]

**Pull request merged**
