### PR TITLE
Better capability create slack message

### PR DESCRIPTION
**Pull request by abstrask**
Commands formatted as code, added line breaks and some basic formatting, to make capability creation Slack messages more legible.

I have tested the string manipulation in a local dummy app, but not sure how to test this in Harald. Review requested :)

### CODE REVIEW

**Comment by devex-sa** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |10|
| **Quality Gates** |OK|
| **Description** |High Risk (10 where 10 is the highest): The risk is higher as much of the code in this repo (99% of all commits) is written by other authors.|

**Comment by abstrask** [comment]
I mean, it's not that I don't agree with CodeScene on this, but damn! That's harsh!

**Review by wcarlsen — APPROVED** [review]
LGTM!

**Review by dfds-pwes — APPROVED** [review]
All looks good to me.  :-)

**Review by avnes — APPROVED** [review]

**Review by ZaradarDFDS — APPROVED** [review]

**Pull request merged**
