### PR TITLE
- Changed emoji codes to use custom emojis

### PR DESCRIPTION
**Pull request by ZaradarDFDS**

### CODE REVIEW

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |1|
| **Quality Gates** |OK|
| **Description** |The change is low risk as it touches fewer modules than your typical change set. It adds 6 lines, deletes 6 lines of code|

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |6|
| **Quality Gates** |OK|
| **Description** |The change is medium risk as it is more diffused (11 files modifified, 90 lines added, 18 lines deleted) than your typical change set. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping code health checks for those files.</li></ul>|

**Comment by SEQUOIIA** [comment]
Cherry-picked the emoji commit to a separate PR, the rest seemed rather out of scope.

**Comment by kim-lindhard-dfds** [comment]
[//]: # (4744e426-5795-11e9-8647-d663bd873d93)

|| **CodeScene Delta Analysis Results** |
| --- | ---- |
| **Risk** |6|
| **Quality Gates** |OK|
| **Description** |The change is medium risk as it is more diffused (11 files modifified, 90 lines added, 18 lines deleted) than your typical change set. The risk is lower since it is a very experienced author with many contributions.|
| **Warnings** |Delta Analysis Info<br/><ul><li>1 files in this change set did not exist with the same name on the main branch. This is probably because those files have been renamed or introduced in the commits under analysis. Skipping code health checks for those files.</li></ul>|

**Pull request closed without merging**
